version: '3.0'

services:
  db:
    build:
      context: ./docker/database
    container_name: trade_cube_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: trade_cube
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3307:3307"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
    networks:
      - symfony

  trace_cube:
    build:
      context: ./docker/apache
    container_name: trade_cube_symfony
    depends_on:
      - db
    volumes:
      - .:/var/www/html/symfony-test-desygner/desygner/
    ports:
      - 2520:8050
    restart: always
    entrypoint: sh /var/www/html/symfony-test-desygner/desygner/apache/start_server.sh
    networks:
      - symfony

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: trade_cube_phpmyadmin
    links:
      - db
    restart: always
    ports:
      - 8089:80
    environment:
      PMA_HOST: trade_cube_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - symfony

networks:
  symfony:
